### ISSUE TITLE
如果要对弹幕的label加入点击事件该怎么做？

### ISSUE THREAD

**Issue by yuxingmin** [unash/BarrageRenderer#11]
如果要对弹幕的label加入点击事件该怎么做？

**Comment by unash** [comment]
目前是不支持各种UI事件的，个人觉得，这不是弹幕范畴之内的事情。
如果想添加点击事情，需要在BarrageCanvas的实现中，设置  self.userInteractionEnabled = YES;
另外，在UILabel上添加点击的UIGestureRecognizer，这些都是需要修改BarrageRenderer框架的，并且可能造成一些潜在问题。
不推荐这么做。
