### ISSUE TITLE
Is this project a static library? I have tried a lot to import this project into mine. I have made a lot of mistakes during importing,the right way is to create a  podfile. After solve the problem, i want to know if this project is a static library. Thank you !

### ISSUE THREAD

**Issue by DanielYQ** [unash/BarrageRenderer#12]

**Comment by unash** [comment]
It is not a static library as all it contains are source code files.
Instead of running pod install, you can also drag the main folder "BarrageRenderer" into your project. That is all you need to do!
By the way, why do you use English?

**Comment by DanielYQ** [comment]
oh,thanks a lot...Because i  want to get more support..
