### ISSUE TITLE
在view上添加了弹幕，在程序运行期间崩溃

### ISSUE THREAD

**Issue by ChangeBegin** [unash/BarrageRenderer#13]
我的数据源是200条数据，当执行到200条之后就报了这个错误，是执行完还要什么操作吗？
libc++abi.dylib: terminate_handler unexpectedly threw an exception
- (void)setAllViews{
    [self initBarrageRenderer];
    
    NSSafeObject * safeObj = [[NSSafeObject alloc]initWithObject:self withSelector:@selector(autoSendBarrage)];
    _timer = [NSTimer scheduledTimerWithTimeInterval:0.5 target:safeObj selector:@selector(excute) userInfo:nil repeats:YES];
}

- (void)initBarrageRenderer
{
    _renderer = [[BarrageRenderer alloc]init];
    _renderer.view.backgroundColor = UIColorFromRGB(SubjectColorValue);
    _renderer.canvasMargin = UIEdgeInsetsMake(0, 0, 70, 0);

    [self addSubview:_renderer.view];
    [self sendSubviewToBack:_renderer.view];
}
- (void)setDataStartWith:(NSMutableArray *)loadArray{
    
    _modelArr = [NSMutableArray array];
    for (NSDictionary *tempDict in loadArray) {
        BarrageModel *model = [[BarrageModel alloc]initWithDict:tempDict];
        [_modelArr addObject:model];
    }
    [_renderer start];
}
- (void)autoSendBarrage{
    NSInteger spriteNumber = [_renderer spritesNumberWithName:nil];
    if (spriteNumber <= 20) {
        [_renderer receive:[self walkTextSpriteDescriptorWithDirection:BarrageWalkDirectionR2L]];
    }
    
}

- (BarrageDescriptor *)walkTextSpriteDescriptorWithDirection:(NSInteger)direction
{
    BarrageModel *model = _modelArr[_index];
    BarrageDescriptor * descriptor = [[BarrageDescriptor alloc]init];
    descriptor.spriteName = NSStringFromClass([BarrageWalkTextSprite class]);
    descriptor.params[@"text"] = [NSString stringWithFormat:@"%@ %@",model.UserNick,model.content];
    descriptor.params[@"textColor"] = [UIColor blueColor];
    descriptor.params[@"speed"] = @(100 * (double)random()/RAND_MAX+50);
    descriptor.params[@"direction"] = @(direction);
    descriptor.params[@"trackNumber"] = @20; // 轨道数量

    _index ++;
    return descriptor;

}

**Comment by unash** [comment]
你的调用方式有问题。
_index 一直在自增，而你的loadArray是有限的。
造成了数组越界。
