### ISSUE TITLE
初始化弹幕后，第一条弹幕是正常从边缘滑动出来的（假设从右到左的弹幕），而是距离右边屏幕一段距离闪现。

### ISSUE THREAD

**Issue by casscqt** [unash/BarrageRenderer#16]
初始化弹幕后，第一条弹幕是正常从边缘滑动出来的（假设从右到左的弹幕），而是距离右边屏幕一段距离闪现。后面的字幕都是正常的。请问这是Bug吗？

**Comment by unash** [comment]
是个bug, 已经修复. 可以直接拉取工程最新代码，cocoapod等下个版本release。
