### ISSUE TITLE
请问能否支持由下向上增长的滚动弹幕？

### ISSUE THREAD

**Issue by LittleChuan** [unash/BarrageRenderer#17]
demo中都是自上向下排布，能否改改成自下向上？

**Comment by unash** [comment]
typedef NS_ENUM(NSUInteger, BarrageFloatDirection) {
    BarrageFloatDirectionT2B = 1,     // 上往下
    BarrageFloatDirectionB2T = 2      // 下往上
};

参考此处。

**Comment by LittleChuan** [comment]
多谢多谢！
