### ISSUE TITLE
请问没有碰撞检测么

### ISSUE THREAD

**Issue by IceCreamWu** [unash/BarrageRenderer#18]
比如在视频某个时间点有很多弹幕，这个时候所有弹幕都重叠在了一起，这个目前有解决方案么？

**Comment by unash** [comment]
如果弹幕很多，叠在一起是必然的。除非使用者对弹幕进行限流。
如果弹幕少，视频某个时间点有很多弹幕，这是弹幕是不会重复的。后来的弹幕总能找到没用到的轨道。

**Comment by gank0326** [comment]
BarrageWalkDirectionR2L BarrageFloatDirectionB2T 同时设置这两个？我现在需要从又往左出来，先出来的要在最下面显示。这个以后会支持吗？我自己人为改变origin 会乱

**Comment by unash** [comment]
我在考虑添加，但是近期不一定能抽出时间来。
