### ISSUE TITLE
怎么设置轨道顺序？

### ISSUE THREAD

**Issue by gank0326** [unash/BarrageRenderer#19]
现在默认第一轨道在顶部，第一条弹幕就是从最上面出来，有设置让第一个弹幕从最下面出来的方法吗？

**Comment by unash** [comment]
[#17](https://github.com/unash/BarrageRenderer/issues/17)

**Comment by gank0326** [comment]
BarrageWalkDirectionR2L    BarrageFloatDirectionB2T   同时设置这两个？我现在需要从又往左出来，先出来的要在最下面显示。

**Comment by gank0326** [comment]
#import "BarrageWalkSprite.h"

@interface BarrageWalkELBarrageViewSprite : BarrageWalkSprite<BarrageELBarrageViewProtocol>

@end

#import "BarrageWalkELBarrageViewSprite.h"
#import "ELBarrageView.h"
#import "ELBarrageModel.h"

@implementation BarrageWalkELBarrageViewSprite

@synthesize model = _model;

- (instancetype)init
{
    if (self = [super init]) {
        _model = nil;
    }
    return self;
}

#pragma mark - launch

- (UIView *)bindingView
{
//    ELBarrageModel *barrage = (ELBarrageModel *)_model;
//    float width = [ELLiveRoomUtil widthForString:barrage.text fontSize:14.0];
//    width = MIN(width, 250);
//    width = MAX(width, 150);
//    width = width+100;
//    
    ELBarrageView *barrageView = [[ELBarrageView alloc] initWithFrame:CGRectMake(0, 0, 375, 36)];
    barrageView.backgroundColor = [UIColor redColor];
    [barrageView fillWithBarrage:_model];
    return barrageView;
}

@end

我继承你的写了一个Sprite，我把bindview 宽度设的足够大，还是会出现重叠

**Comment by unash** [comment]
『BarrageWalkDirectionR2L BarrageFloatDirectionB2T 同时设置这两个？我现在需要从又往左出来，先出来的要在最下面显示。』这个是不支持的。

**Comment by unash** [comment]
『(UIView *)bindingView { ELBarrageView *barrageView = [[ELBarrageView alloc] initWithFrame:CGRectMake(0, 0, 375, 36)]; [barrageView fillWithBarrage:_model]; return barrageView; }』
在bindingView里设置frame不起作用，需要在你的ELBarrageView里面实现 sizeThatFits方法返回ELBarrageView真实的大小。比如返回(375, 36)。

**Comment by gank0326** [comment]
『(UIView *)bindingView { ELBarrageView *barrageView = [[ELBarrageView alloc] initWithFrame:CGRectMake(0, 0, 375, 36)]; [barrageView fillWithBarrage:_model]; return barrageView; }』
在bindingView里设置frame不起作用，需要在你的ELBarrageView里面实现 sizeThatFits方法返回ELBarrageView真实的大小。比如返回(375, 36)。


写在sizeThatFits这边会很卡
