### ISSUE TITLE
BarrageClock never got released.

### ISSUE THREAD

**Issue by mingweizhang** [unash/BarrageRenderer#21]
Some logic bugs in BarrageClock class.Here is my PR(#20 )

**Comment by unash** [comment]
I committed a new version 1.8.0, you can try this.

**Comment by mingweizhang** [comment]
I have tried the new version(1.8.0).It doesn't work for this issue.And after I checked the codes u committed recently,I couldn't find the commit which fixed this issue.Could u show me the codes or the commit link?

**Comment by unash** [comment]
Which version did you use before? 1.7.0?

**Comment by mingweizhang** [comment]
Yes,1.7.0.And I tried the newest codes on branch master after you release version 1.8.0.
pod 'BarrageRenderer', :git => 'https://github.com/unash/BarrageRenderer.git'

**Comment by mingweizhang** [comment]
Take a look at my new PR #22

**Comment by unash** [comment]
this: https://github.com/unash/BarrageRenderer/commit/5ae48631e022c1b86a0994c7c1915bf8469b4d76

which fix a retain cycle in 1.7.0

And the commit was released in 1.8.0

**Comment by mingweizhang** [comment]
Yeah.I fixed the BarrageRenderer retain cycle issue by the same codes.
But this is another issue of BarrageClock.

**Comment by mingweizhang** [comment]
Have u got it?

**Comment by unash** [comment]
Does it appear in the demo?

**Comment by mingweizhang** [comment]
The demo couldn't reproduce this issue.Because the demo keeps a View Controller as root view controller all the time.And VC keeps BarrageRenderer instance all the time.

**Comment by unash** [comment]
I merged it into master branch.

**Comment by mingweizhang** [comment]
OK.I closed this issue.
