### ISSUE TITLE
自定义View

### ISSUE THREAD

**Issue by coderLeonLi** [unash/BarrageRenderer#23]
最近在做直播的项目，恰好找到您这个BarrageRenderer，非常高兴，现在我想模仿其他App（inke）的弹幕功能，就是弹幕是在收到socket时动态产生，弹幕主题由用户头像、用户昵称、用户发言内容组成，要求用户头像可以点击，进入用户的个人主页，现在想请教下，这个能否用BarrageRenderer实现，并说下大致思路；或者自己写一个view，然后动画从右至左，然后解决复用；哪种比较好？

**Comment by unash** [comment]
可以实现，不过目前默认支持整个弹幕的点击，如果用Button实现头像点击的话，你需要处理好点击事件的传递。
