### ISSUE TITLE
手势无响应.

### ISSUE THREAD

**Issue by xclidongbo** [unash/BarrageRenderer#28]
给的方法无效. 如果底层视图有手势,则不响应点击事件.

**Comment by unash** [comment]
底层视图，是指『父view』还是『叠放在下面的view』？

**Comment by binkylee888** [comment]
遇到的也是同样的问题，手势不响应，不知道出现这种问题的原因是什么

**Comment by unash** [comment]
把相关代码发我来，我看看。

**Comment by binkylee888** [comment]
找到问题的原因了，在引用BarrageRenderer的viewController里，也引入了一个UILabel的类目，类目中也重写了- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event，事件被拦截
