### ISSUE TITLE
希望可以对初始显示的轨道，进行设置。

### ISSUE THREAD

**Issue by zzgo** [unash/BarrageRenderer#31]
首先感谢作者的付出。
现在默认都是上往下，我希望第一个出现的轨道，是最底部的轨道。
我试着继承 BarrageWalkTextSprite , 然后覆盖- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites 返回你设置的弹幕初始位置.
```
- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites
{
    CGPoint point = [super originInBounds:rect withSprites:sprites];
    return point+200;
}
```
初始位置改变了，但是路线，变成了从”右下->左上“的斜线。

希望可以添加一个接口，设置初始显示的轨道。谢谢

**Comment by unash** [comment]
更新到1.9.0版本，支持了从右到左运动事，从底部往上堆叠，以及相关的运动属性。参照[这里](https://github.com/unash/BarrageRenderer#设置靠边位置)。

**Comment by zzgo** [comment]
修改很迅速，非常感谢。
