### ISSUE TITLE
mandatorySize 如何使用

### ISSUE THREAD

**Issue by YBYHunter** [unash/BarrageRenderer#34]
mandatorySize 如何使用

**Comment by unash** [comment]
> 你也可以在创建弹幕描述符的时候强制指定弹幕元素的大小。通过设置：
> 
> BarrageDescriptor.params[@"mandatorySize"]
> 
> 设置此属性之后，你自定义的弹幕 view 的 - (CGSize)sizeThatFits 将不再起作用，但是覆盖的 - (CGSize)size 方法仍然是有效的，因为它的优先级比较高。
> 
>
