### ISSUE TITLE
视频快进快退弹幕处理

### ISSUE THREAD

**Issue by ajjing** [unash/BarrageRenderer#35]
如果播放视频到15s，快退5s，这时是10s的时候。之前10s-15s播放过的弹幕不会再播放吗，需要再等到视频15s的时候才能继续播弹幕？
如果要实现10s-15s的时候播放快退前播放过的弹幕，应该怎么处理这块逻辑？

**Comment by unash** [comment]
『如果播放视频到15s，快退5s，这时是10s的时候。之前10s-15s播放过的弹幕不会再播放吗，需要再等到视频15s的时候才能继续播弹幕？』
**如果 10s~15s之间出来的弹幕已经从屏幕上消失的话，那么从10s开始，这部分弹幕会再重新播一遍；但是如果在这之间的弹幕已经在屏幕上了，就不会再播放。**

『如果要实现10s-15s的时候播放快退前播放过的弹幕，应该怎么处理这块逻辑？』
**你在代理方法 - (NSTimeInterval)timeForBarrageRenderer:(BarrageRenderer *)renderer 中返回正确的当前播放时间轴时间，就可以了。**

**Comment by JiangqiQAQ** [comment]
- (NSTimeInterval)timeForBarrageRenderer:(BarrageRenderer *)renderer
{
    //返回视频播放的时间轴
    return (CGFloat)CMTimeGetSeconds([_player currentTime]);
}
