### ISSUE TITLE
请问是否可以指定弹幕显示出来的位置

### ISSUE THREAD

**Issue by lixiaonan** [unash/BarrageRenderer#36]
用户发送的弹幕显示在上下,或者中间(或者是某行),,,由用户指定,请问是否提供了这样的接口呢

**Comment by unash** [comment]
目前是不支持的。
你可以通过方法继承，覆盖 originInBounds:withSprites: 这个方法来实现。

**Comment by CavanZhao** [comment]
我设置了tracNum = 3; 为什么都是在同一行显示

**Comment by unash** [comment]
@lixiaonan 没有提供，你需要继承 sprite，并覆盖
- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites;
返回你的初始位置

**Comment by unash** [comment]
截图我看下？ @CavanZhao
