### ISSUE TITLE
设置弹幕的显示位置.一开始无效,横屏后才有效

### ISSUE THREAD

**Issue by lixiaonan** [unash/BarrageRenderer#37]
设置弹幕的显示位置canvasMargin, 一开始竖屏时没有这样的效果,横屏后才有效.......Demo中的代码
_renderer.canvasMargin = UIEdgeInsetsMake(100, 10, 10, 10);

**Comment by lixiaonan** [comment]
demo中也有这样的问题

**Comment by unash** [comment]
修复了，拉取最新代码可以看看更改。
等下次release时再发布。

**Comment by unash** [comment]
已在 1.9.1 版本修复。

**Comment by unash** [comment]
已在 1.9.1 版本修复。
