### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by Chakery** [unash/BarrageRenderer#38]
初始化的时候崩溃了。本人的需求是需要经常的添加，删除弹幕。（经常init，removeFromSuperView）

初始化代码如下：

```
private var render: BarrageRenderer! //弹幕

render = BarrageRenderer()
render.redisplay = true
renderBackgroundView.addSubview(render.view)
renderBackgroundView.sendSubviewToBack(render.view)
render.start()
```

崩溃信息如图：
![qq20161019-0](https://cloud.githubusercontent.com/assets/9679029/19511116/79c8aba8-9618-11e6-8896-4828a4f7c4ec.png)

**Comment by unash** [comment]
多次添加、删除的整个生命周期发上来看下。

**Comment by Chakery** [comment]
你可以先看下我大概的一个结构，如下：
![qq20161020-0](https://cloud.githubusercontent.com/assets/9679029/19543603/4abd8bb0-96ab-11e6-96ab-4276c39eb85d.png)

但是，经过我多次反复的测试之后发现：
1. 移除“弹幕的父视图”是没问题的；
2. 移除“弹幕的父视图”之后，并且`弹幕父视图 = nil`，这个时候才会崩掉。

**Comment by Chakery** [comment]
ok，解决了。
大概问题是，在释放的时候需要停止”弹幕“。在父视图销毁的时候，停止并移除弹幕。

```

deinit {
    destroyBarrageRender()
}



func destroyBarrageRender() {
    if barrageRender != nil {
        barrageRender.stop()
        barrageRender.view.removeFromSuperview()
        barrageRender = nil
    }
}
```
