### ISSUE TITLE
弹幕显示的区域/行数限制问题

### ISSUE THREAD

**Issue by ACoderBear** [unash/BarrageRenderer#41]
当我设置弹幕view的edges之后，比如底部留下1/3的位置不显示，当横屏下弹幕数量较多，我切回竖屏的时候，屏幕上的弹幕会被切，view的布局更新了，但是弹幕本身的布局还是横屏的，就会被view的边缘砍到。
另：有没有灵活的改变字体大小的方法呢？
另：每次load都会导致所有弹幕全部从当前时间加载，而不会按照播放时间加载~descriptor能提供timestamp参数么，当前用的是delay

**Comment by unash** [comment]
1. 切回竖屏之后，屏幕上已经显示的弹幕坐标是没有改变的，所以会有短暂的显示异常。你想要的是什么效果呢？
2. 你是指运动的时候改变字体大小？
3. 你是在启动的时候load还是播放过程中多次load?

**Comment by ACoderBear** [comment]
1. 切回竖屏之后布局更新，显示正常
2. 需求是横竖屏的字体大小不一样，也相当于运动的时候改变字体大小吧
3. 这条其实是为了解决2在播放过程中load，然后发现load之后内部时间和视频时间不匹配了，所以弹幕显示的时间点就会错

**Comment by ACoderBear** [comment]
补充：3的情况其实就是我在播放一段时间后load弹幕，弹幕不会在delay后的时间点出现，而是从当前时间作为初始时间去加载delay，也就是并没有根据视频播放的时间去匹配delay的值。描述的有点乱，希望能看懂

**Comment by unash** [comment]
1,2 两点目前不支持。弹幕发出去之后，内置的弹幕系统就没有控制能力了。下面2种方法都比较麻烦：
a. 可以试试在转屏幕的时候，先 stop，转屏结束后再 start。使用 1.9.1，之前的stop时有个bug
b. 自定义弹幕，拿到转屏事件，去更新字体与调解坐标

3. delay 确实是根据当前时间作为参照的。所以，如果“播放一段时间后load弹幕”，你需要根据播放的进度，计算一个正确的delay时间。

**Comment by ACoderBear** [comment]
1. 之前试过你说的做法，stop修改字体大小并且重新计算delay之后start并加载弹幕。 
 >这带来另一个问题：stop之后内部重置数据，记录的弹幕会被清空，会打乱记录逻辑，当我回放的时候旋转之前的弹幕就不存在了
2. 为了解决2，就必须在旋转/快进/退时也要做1的逻辑。
3. 想说，一个库不能满足千变万化的需求，我自己想想解决方案，也会关注你的更新。

最后：由衷感谢一下您提供的源码。

**Comment by unash** [comment]
好的，抱歉未能帮到你。
