### ISSUE TITLE
如何实现关闭弹幕再开启弹幕呢？

### ISSUE THREAD

**Issue by smallqiang** [unash/BarrageRenderer#42]
我现在有个功能是用户可以关闭弹幕或者再次开启弹幕，但是我直接用stop然后再start弹幕就不再出现了。请问要怎么去做呢，谢谢！

**Comment by unash** [comment]
原先有个 bug，已经修复。
你可以使用 1.9.1 版本试试，如果 pod 不能拉取，可以在 podfile 中指定 tag＝>'1.9.1' 试试。

**Comment by smallqiang** [comment]
刚更新了最新1.9.1了但是我stop之后再start弹幕还是没有出来了。

**Comment by smallqiang** [comment]
我是想的是像B站那样如果暂时关掉弹幕了然后再按开启弹幕可以把弹幕再重新显示出来，但是看你代码的注释的话是一旦stop了就把之前已经加载的清空了，然后再start也没用了。

**Comment by unash** [comment]
那你这样试试：
使用 pause暂停，同时隐藏 renderer.canvas;
当重新启动时，调用 start，再 renderer.canvas.hidder=NO

**Comment by smallqiang** [comment]
好的，我试试但我们项目还有一个很蛋疼的需求就是关闭了弹幕后看不到别人的弹幕，但是自己发送出去的可以显示出来，所以不知道有没有一些参数可以设置，就如加入一些tag来标识，黑名单和白名单这样子，那自己发送的就可以显示出来了。

**Comment by smallqiang** [comment]
但是如果像你这样把整个view隐藏了那之后再显示出来也很怪。因为像B站那样，关闭后再开启弹幕是重新从屏幕外滚出来的。

**Comment by unash** [comment]
实现过类似的需求。但BarrageRenderer本身没有开关，你需要在业务层面做。
发送弹幕时，包装一下弹幕数据，比如{userId:"xxx", data:"这是弹幕数据"}，拿到数据的时候，与当前用户对比。

**Comment by unash** [comment]
暂停/开启 周边的逻辑没有仔细写，因为好多需求也不一样；
后面有时间了，我会考虑把这样的定制接口写出来；
你如果看明白代码的话，也可以考虑一下这个接口的设计，然后commit上来。

**Comment by smallqiang** [comment]
是不是只能设置delay参数来显示弹幕在哪个时间点显示。不能设置一个秒数来显示吗？例如我现在做的就是把弹幕stop后重新再load弹幕然后start来实现，但是视频是一直在播的，但弹幕还是重新再显示。

**Comment by unash** [comment]
嗯，目前是用delay标记时间位置。而且 delay 是相对 receive: 的时刻起作用的。
stop 之后 重新load时，你可能就需要调整delay的值了。

**Comment by smallqiang** [comment]
有参数可以设置弹幕之间的上下距离吗，我看到的是要整个view来设置的，但我只是想统一他们之间的间距。

**Comment by smallqiang** [comment]
还有我想调整字体的大小是通过哪个参数呢？

**Comment by unash** [comment]
不能动态地改变字体，只能创建descriptor的时候设置：
descriptor.params[@"fontSize"] = @(14);

**Comment by unash** [comment]
[有参数可以设置弹幕之间的上下距离吗，我看到的是要整个view来设置的，但我只是想统一他们之间的间距。]
你可以将trackNumber设置的小一些，比如10，应该可以达到类似弹幕间距的效果。

**Comment by smallqiang** [comment]
嗯现在也是根据设计稿来设置好高度，然后轨道数来实现间距效果。
