### ISSUE TITLE
请问我用富文本弹幕 从新设置了 宽度后 文字不居中了 

### ISSUE THREAD

**Issue by MarkTangs** [unash/BarrageRenderer#45]
<img width="210" alt="68c679df-2f71-4dd9-8fb8-1992f513a65a" src="https://cloud.githubusercontent.com/assets/13257622/21417501/f9bbc43e-c855-11e6-9b31-6d05de4e6b79.png">

我该怎么让文字居中呢？

**Comment by unash** [comment]
"从新设置了 宽度", 怎么设置的？目前没有提供设置宽度的接口啊？
如果是用的demo中的BarrageWalkImageTextSprite，设置一下 label.textAlignment = NSTextAlignmentCenter; 就可以了。
