### ISSUE TITLE
BarrageClock.h请引入UIKit.h

### ISSUE THREAD

**Issue by hegelsu** [unash/BarrageRenderer#50]
我是复制的文件来编译为.a库的，这里少个引入，没什么大问题。

另外我想说我的效果是这样的：
从最左下方一行一行往上弹，发一个弹一个，最后发的在最下面，发一下把前面发的依次往上弹一个位置，就像聊天框那样的效果，不知道这个要用你的库怎么弄才好，给个思路吧。

**Comment by unash** [comment]
这个用弹幕实现可能并不合适，自己写sprite会比较复杂。
你可以在左侧添加一个tableView，然后弹幕作为cell添加上去。

**Comment by hegelsu** [comment]
好的，谢谢。
