### ISSUE TITLE
弹幕出现时机和位置

### ISSUE THREAD

**Issue by CavanChio** [unash/BarrageRenderer#54]
控制tracNum = 3, 让每个弹幕出现在屏幕的某个位置时, 进入下个弹幕, 下个弹幕出现在前一个弹幕的某个位置, 怎么设置

**Comment by CavanZhao** [comment]
另外点击弹幕也没有响应

**Comment by unash** [comment]
相对于前一条弹幕的位置是自动计算的，除非你自己计算
- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites;
点击弹幕需要注入 clickAction；如果设置了，检查一下视图层级。

**Comment by CavanZhao** [comment]
因为弹幕是不定时出现的, 这个sprites数组里面存的是哪些弹幕, 还是只要是发的弹幕都存在这个数组里面?

**Comment by unash** [comment]
sprites 里面存的是当前显示的弹幕

**Comment by CavanZhao** [comment]
现在遇到两个问题, 第一个: 直播过程中用户需要发弹幕时, 是不是用户点击发送就让他调用recieve方法, 然后自动将用户发的弹幕加入waitingSprites数组中, 等待加入屏幕?还是需要我进行处理加入数组的操作

**Comment by CavanZhao** [comment]
现在遇到两个问题, 第一个: 直播过程中用户需要发弹幕时, 是不是用户点击发送就让他调用recieve方法, 然后自动将用户发的弹幕加入waitingSprites数组中, 等待加入屏幕?还是需要我进行处理加入数组的操作;  另外如果等待出现的弹幕过多的时候, 会出现重叠的现象, 这个该怎么处理(我设置的速度恒定, 并非变速弹幕)? 希望能得到解答, 谢谢

**Comment by unash** [comment]
【1】直播中，用户点击「发送」之后，可以直接调用recieve方法，就直接显示在屏幕上了；如果需要延时上屏，填上delay参数就可以了
【2】为防止重复，一个比较好的实践是，你调用 receive 之前，创建一个过滤器。可以根据一些规则（比如屏幕上的弹幕数量）来决定是否上屏/设置delay。这种规则应该是一个经验值。

**Comment by CavanZhao** [comment]
比如我设置最大航道为3, 如果我想开辟三个子线程分别管理三个航道上弹幕队列, 能不能实现不重叠的效果, 如果这样可行, 我应该在源码哪里添加这个逻辑比较好,谢谢

**Comment by CavanZhao** [comment]
另外我觉得设置延时也不是一个最好的解决办法, 因为一旦开启弹幕, 假如有大量的弹幕, 但又没有达到最大数量, 依然会出现重叠的现象, 有没有一个时刻让我能够处理要添加的弹幕的前一个弹幕完全进入屏幕的时候添加该弹幕, 如果没有完全进入屏幕, 则就不能加入该弹幕

**Comment by unash** [comment]
针对其中的一条轨道，计算一下一条弹幕从进入到完全显示出来的时间T，然后在每次receive前，登记一下时间信息t0；当下一条弹幕t1过来的时候，比照t1-t0与T的关系，如果不能重复，就放行；否则，延时。
这样呢？

**Comment by CavanZhao** [comment]
这样的确是个目前来说比较不错的解决办法, 因为我用的是自定义的弹幕, 然后在bindingView的方法里面返回了自定义的view, sprites数组里面存的是不是我自定义的view, 另外我再(CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites方法里面返回一个位置, 初始位置是对的, 但是弹幕消失的位置依旧在原来的第一个巷道上, 能不能定义好一个初始位置, 让弹幕水平移动, 我该怎么处理呢

**Comment by unash** [comment]
你应该是继承自 BarrageWalkTextSprite 吧。
- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites，方法返回 初始位置
但这里有个设计不好的地方，需要在这个方法里面，初始化 _destination 的值。你看一下 185行代码附近。

**Comment by CavanZhao** [comment]
确实是继承这个BarrageWalkTextSprite, 您说的初始化时怎么样进行操作?看的时间比较短, 还是没有太明白

**Comment by unash** [comment]
参考这一段：https://github.com/unash/BarrageRenderer/blob/master/BarrageRenderer/BarrageSprite/BarrageWalkSprite.m#L184-L194
大概就是，你确定了你的 起点位置 之后，再计算一下目标位置。横向walk的，就加个rect.width+sprite.width之类的。

**Comment by CavanZhao** [comment]
恩, 我先调试下, 麻烦了, 谢谢

**Comment by CavanZhao** [comment]
_destination.x本身位置没问题, 但是如果是水平弹幕的时候, 其实我只需要改下_destination.y的位置就可以了, 但是我看源码
_destination.y = origin.y = (rotation?stripHeight*availableFrom:rect.size.height-stripHeight * availableFrom-self.size.height)+rect.origin.y;不是很明白这些运算的思路

**Comment by unash** [comment]
这些主要是针对 上->下，下->上 等方向的弹幕作的抽象，如果你的弹幕方向比较单一，不用考虑这些问题。
只不过，这时候，你弹幕的 params[@"direction"] 可能就无效了。

**Comment by CavanZhao** [comment]
我的弹幕方向就是从右到左的, 正常情况下下一步弹幕应该是插入最短的那一列, 但是我的弹幕形式是第二条插入第一条下面一行, 第三条插入第二条下面, 然后第四条插入第三条上面这样的逻辑循环. 所以我想在(CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites自定义弹幕出现的初始位置, 但是这样初始位置是正确的, 但是终点位置就不是水平从右到左了, 它变成从第三行斜着运动到第一行的左边, 所以我还是不太明白应该怎么修改_destination.y的位置

**Comment by unash** [comment]
如果是水平方向的，_destination.y = origin.y 就可以了。

**Comment by CavanZhao** [comment]
将外界获取到的弹幕数据加到一个数组里面, 这样这个数组在实时刷新过程中是不断在变化的, 我该怎么处理将这个变化数组中的弹幕数据按顺序一条条显示出来呢或者有什么好的弹幕实现方法

**Comment by unash** [comment]
回复总不及时 ╮(╯▽╰)╭
这个问题在 2.0.0 之后处理了，BarrageRenderer 内部增加了根据 delay 增序的队列，由此能够保证弹幕的出现顺序严格遵照 delay 标识的时刻。
不过 V2 版本与 V1 版本并不完全兼容，若要升级推荐多测测。
