### ISSUE TITLE
图文混合的弹幕有没有属性设置后面的文字的中心点等于图片的中心点呢？

### ISSUE THREAD

**Issue by Mr-lins** [unash/BarrageRenderer#59]
![5834444b-9b3e-42ea-aed6-e04f8a1e0056](https://cloud.githubusercontent.com/assets/26573094/26709708/3926cfdc-4787-11e7-9c58-51eaf5ad008b.png)

**Comment by Mr-lins** [comment]
就是中心点对齐，还有图片是否可以切圆角？

**Comment by unash** [comment]
BarrageRenderer 默认是使用的 UILabel 做的图文混合，这种效果是比较单一的；相当于你要在 Label 里做 中心点对齐/切圆角 操作，估计也挺局限。

**Comment by komayip** [comment]
用自定義的view就可以了
