### ISSUE TITLE
ld: library not found for -lBarrageRenderer

### ISSUE THREAD

**Issue by kakaluo** [unash/BarrageRenderer#6]
下载整个工程，pod update之后再运行提示这个错误：
ld: library not found for -lBarrageRenderer
frameworks中的.a文件是红色的

**Comment by unash** [comment]
运行下 pod search BarrageRenderer 看看有没有结果。

**Comment by kakaluo** [comment]
![qq 20151027181122](https://cloud.githubusercontent.com/assets/7160316/10755012/278c777c-7cd6-11e5-861a-518889f39e88.jpg)

**Comment by kakaluo** [comment]
导入自己工程，提示找不到BarrageRenderer.h；
自己工程中pod install，还是提示ld: library not found for -lBarrageRenderer

**Comment by kakaluo** [comment]
可以了，install再update一下，打开workspace可以正常运行了
