### ISSUE TITLE
是否可以添加一个弹幕将要滑出屏幕的代理

### ISSUE THREAD

**Issue by GodL** [unash/BarrageRenderer#60]

**Comment by unash** [comment]
这个可以，我想想怎么加。
你的具体需求可以描述下，我做个参考。
另外，使用的 BarrageRenderer 的版本号？

**Comment by GodL** [comment]
我希望当一个弹幕滑出屏幕时，让它再次滑入

**Comment by unash** [comment]
有两种设计方案可以拿到弹幕元素的进出屏幕的时间：
1. 为 descriptor 添加 action 回调
2. 为 renderer 添加代理
目前 develop 分支最新代码，我通过第2种方法提供了 sprite 的进出屏幕时机。代理方法如下：
- (void)barrageRenderer:(BarrageRenderer *)renderer spriteStage:(BarrageSpriteStage)stage spriteParams:(NSDictionary *)params。
其实方案2也可以通过业务方继承 renderer 来实现。
