### ISSUE TITLE
对象销毁的时候，初始化时钟里面的block中的self为 nil时奔溃，strongSelf 没有做判空

### ISSUE THREAD

**Issue by againxu** [unash/BarrageRenderer#62]
/// 初始化时钟
- (void)initClock {
    __weak id weakSelf = self;
    _clock = [BarrageClock clockWithHandler:^(NSTimeInterval time) {
        BarrageRenderer *strongSelf = weakSelf;
        if (strongSelf) {
            strongSelf->_time = time;
            [strongSelf update];
        }
    }];
}

**Comment by unash** [comment]
使用属性来处理这个问题了。
https://github.com/unash/BarrageRenderer/commit/8a06782774c1c3cfa2ba3a5b97c1112ef695b39a
