### ISSUE TITLE
暂停功能有bug？

### ISSUE THREAD

**Issue by LeoFangQ** [unash/BarrageRenderer#7]
加了快进快退功能之后，原来的暂停/恢复功能好像不行了

**Comment by unash** [comment]
具体描述一下？想要什么样的效果，怎么操作的，出现了什么现象？

**Comment by LeoFangQ** [comment]
比如“过场弹幕：5”出现的时候 我点击暂停功能 隔一会点击恢复 这时候屏幕会飘过“过场弹幕：0”、“过场弹幕：1” 相当于又重新开始了

**Comment by unash** [comment]
请拉取1.6.0版本试试,问题应该解决了.
