### ISSUE TITLE
link错误

### ISSUE THREAD

**Issue by jsaddnf** [unash/BarrageRenderer#76]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BarrageWalkTextSprite", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_BarrageDescriptor", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_BarrageRenderer", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

在新工程里导入无法编译，初始化方法和demo的一致。

尝试导入.m以及修改Other linker flag亦无效。

**Comment by jsaddnf** [comment]
运行环境是Xcode 9.0，iOS 11

**Comment by unash** [comment]
可能是 merge 引起的问题。
你尝试使用 2.1.0 版本试试。

**Comment by jsaddnf** [comment]
已经尝试过更新到2.1.0版本。还是如此情况

**Comment by unash** [comment]
换成真机试一下？

**Comment by unash** [comment]
换成真机试一下？

**Comment by jsaddnf** [comment]
也换成真机测试过了。一样的问题。项目需要的依赖库我也照着Demo引入了一遍，仍然无法编译通过。

**Comment by unash** [comment]
1. 确定一下 pod 是否已经成功拉取
2. 看一下是哪些 symbol 没有找到

**Comment by jsaddnf** [comment]
解决了。通过pod导入会有一个.a文件生成，手动导入缺失这个.a文件，手动再导入.a文件并链接就能编译了。
