### ISSUE TITLE
seek之后暂停，时钟系统乱了

### ISSUE THREAD

**Issue by LeoFangQ** [unash/BarrageRenderer#8]
外部播放器seek 改变_predictedTime的值通过代理方法timeForBarrageRenderer: 传递到弹幕库，接着执行pause方法，时间好像乱了。

**Comment by unash** [comment]
- (NSTimeInterval)timeForBarrageRenderer:(BarrageRenderer *)renderer
这个实现粘过来看看.

**Comment by LeoFangQ** [comment]
- (NSTimeInterval)timeForBarrageRenderer:(BarrageRenderer *)renderer
{
    NSTimeInterval interval = [[NSDate date]timeIntervalSinceDate:_startTime];
    interval += _predictedTime;
    return interval;
}

_startTime 是播放视频第一帧的时间

**Comment by unash** [comment]
调用方式不对，你直接在(NSTimeInterval)timeForBarrageRenderer:(BarrageRenderer *)renderer
这个方法中返回播放器的当前进度，比如 moviePlayer.currentPlaybackTime。此时_renderer不需调用pause, 也不需用_predictedTime。

**Comment by LeoFangQ** [comment]
解决了，谢谢！
