### ISSUE TITLE
Expose params in BarrageDescriptor class

### ISSUE THREAD

**Issue by wongzigii** [unash/BarrageRenderer#86]
> /// 属性字典
    @property(nonatomic,strong,readonly)NSMutableDictionary * params;

While I initializing a descriptor, I would like to modify the param before the render to receive.
So is this possible to expose the params, eg: textColor or font family to interface file?
At this time, I need to check out the demo to see which are the optional params before I getting start.

**Comment by unash** [comment]
这一点主要是考虑自定义 Sprite，其配置参数也可能自定义。此配置参数由 Descriptor 传过来，而 Descriptor 为统一接口对象，不方便为期添加便捷属性，故使用了字典来传递。

实在需要，只能由业务层自己创建一个转换器了。
