### ISSUE TITLE
shadowColor and shadowOffset not work for UILabel(BarrageView) 

### ISSUE THREAD

**Issue by roylly** [unash/BarrageRenderer#87]
I want to set label.shadowColor while UILabel(BarrageView) set layer.shadowColor like below
self.layer.shadowColor = [UIColor clearColor].CGColor;
and the same problem with shadowOffset.

**Comment by unash** [comment]
为 descriptor 设置下面两个值：
params[@"shadowColor"];
params[@"shadowOffset"]

**Comment by roylly** [comment]
这个可以通过attributedText设置文字阴影和阴影范围。UIlabel的文字阴影是有对应的属性的，就是shadowColor。这个库对于UIlabel，设置了layer.shadowColor。是对整个label做了阴影效果。
总体感觉这个库的API还不是很人性化，通过字典传参，需要知道内部很多参数和逻辑，看看后面能修改一下嘛。

**Comment by unash** [comment]
嗯，我会考虑这个问题。
