### ISSUE TITLE
如何改变一个弹幕的纵坐标

### ISSUE THREAD

**Issue by kakaluo** [unash/BarrageRenderer#9]
如何改变一个从左向右的弹幕的纵坐标，我改变barragewalkspirit里面的几个参数后，所有都变成0了

**Comment by unash** [comment]
默认的sprite 是不能改变坐标的。若想自定义从左向右的弹幕，可以继承 BarrageWalkTextSprite , 然后覆盖- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites 返回你设置的弹幕初始位置.

**Comment by kakaluo** [comment]
明白了，谢谢
