### ISSUE TITLE
如何自定义文字的背景视图

### ISSUE THREAD

**Issue by weiwei1991** [unash/BarrageRenderer#90]
<img width="309" alt="2018-04-03 5 23 56" src="https://user-images.githubusercontent.com/7012340/38241062-d8f6c1e4-3763-11e8-985f-e17339db26e7.png">
可以自定义弹幕文字的背景间距

**Comment by TonyGJJ** [comment]
你好 请问你解决了吗？
我也需要自定义 背景 但是不知道属性怎么给

**Comment by silendir** [comment]
设置间距不生效

**Comment by weiwei1991** [comment]
已解决
