### ISSUE TITLE
`spriteQueueWithDelayLessThan` 里面的逻辑好奇怪

### ISSUE THREAD

**Issue by alfredcc** [unash/BarrageRenderer#98]
目前正在用 swift 改下作者的库，但发现 `spriteQueueWithDelayLessThan` 和 `spriteQueueWithDelayGreaterThan` 这两个方法里面的逻辑好奇怪，可以解释下吗？

**Comment by unash** [comment]
通过这个函数，获取将要播放的弹幕队列。如果启用平滑的话，会在拿到一段时间内的弹幕，并在相应时间范围内均匀分开，这样弹幕播放的时候，就不会突然卡顿。
