### ISSUE TITLE
请问能否实现几个弹幕并排前进的效果（图）

### ISSUE THREAD

**Issue by pikacode** [unash/BarrageRenderer#99]
![6F771A67DC841631D365928B660A7A97](https://user-images.githubusercontent.com/12589575/61203877-387bb680-a71e-11e9-8740-e8050e6bc96d.jpg)

类似如图效果。不希望跟其他弹幕互相覆盖，或者起冲突

**Comment by pikacode** [comment]
![434BD155128D887E04A4A71378BCCB6A](https://user-images.githubusercontent.com/12589575/61204662-66fa9100-a720-11e9-9722-12a82d4efee7.jpg)

这个库是否提供了API，可以判断在 1 2两种情况下，我该将文字排列在何处

**Comment by unash** [comment]
继承 BarrageFloatSprite 自定义弹幕，在其方法：
- (CGPoint)originInBounds:(CGRect)rect withSprites:(NSArray *)sprites;
中，可以拿到目前屏幕上已存在的弹幕，获取这些弹幕的位置，
即可以定义自己的弹幕应该出现在何处。
